import '@/styles/globals.css'
import { Fragment } from 'react'

import { Inter as FontSans } from 'next/font/google'

import { TRPCReactProvider } from '@/trpc/react'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/theme-provider'
import Header from './_components/partials/header'
import Footer from './_components/partials/footer'
import { Toaster } from '@/components/ui/sonner'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'flex min-h-screen flex-col bg-background font-sans text-foreground antialiased',
          fontSans.variable,
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TRPCReactProvider>
            <Fragment>
              <Header />
              {children}
              <Footer />
              <Toaster richColors />
            </Fragment>
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
